export const DEL_HYBIRDIZE='del_hybirdize'
export const EDIT_HYBIRDIZE='edit_hybirdize'
export const EDIT_HYBIRDIZE_END='edit_hybirdize_end'
export const ADD_HYBIRDIZE='add_hybirdize'
export const ADD_HYBIRDIZE_END='add_hybirdize_end'
export const FETCH_HYBIRDIZE='fetch_hybirdize'
export const RECEIVE_HYBIRDIZE='receive_hybirdize'
export const RECEIVE_POST='receive_post'
export const TAB='tab_hybirdize'

